apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "aiapi.fullname" . }}"
  labels:
    {{- include "aiapi.labels" . | nindent 4 }}
type: Opaque
stringData:
  newapi-session-secret: {{ .Values.newapi.sessionSecret | quote }}
  cliproxyapi-config.yaml: |-
    {{- .Values.cliproxyapi.config | nindent 4 }}
