apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-{{ .Chart.Name }}"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-{{ .Chart.Name }}"
    spec:
      {{- if not (empty .Values.nodeSelector) }}
      nodeSelector: {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if not (empty .Values.affinity) }}
      affinity: {{- toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      containers:
        name: "{{ .Release.Name }}-{{ .Chart.Name }}"
          image: "{{ .Values.image.name }}:v{{ .Chart.AppVersion }}"
          ports:
            - containerPort: 80
            - containerPort: 443
            - containerPort: 3478
          env:
            - name: TAILSCALE_HOSTNAME
              value: "{{ or .Values.tailscale.hostname .Release.Name }}"
            - name: TAILSCALE_AUTH_KEY
              value: "{{ .Values.tailscale.auth_key }}"
            - name: TAILSCALE_DERP_HOSTNAME
              value: "{{ .Values.drep.hostname }}"
            - name: TAILSCALE_DERP_ADDR
              value: "{{ .Values.drep.addr }}"
            - name: TAILSCALE_DERP_VERIFY_CLIENTS
              value: "{{ .Values.drep.verify_clients }}"
