{{- if not .Values.hostNetwork }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}"
  {{- if not (empty .Values.service.annotations) }}
  annotations: {{- toYaml .Values.service.annotations | nindent 4 }} 
  {{- end }}
spec:
  type: "{{ .Values.service.type }}"
  selector:
    app: "{{ .Release.Name }}-{{ .Chart.Name }}"
  ports:
    {{- if gt (int .Values.derp.http_port) -1 }}
    - name: http
      port: {{ .Values.derp.http_port }}
      targetPort: {{ .Values.derp.http_port }}
    {{- end }}
    - name: https
      port: {{ .Values.derp.https_port }}
      targetPort: {{ .Values.derp.https_port }}
    - name: stun
      port: {{ .Values.derp.stun_port }}
      targetPort: {{ .Values.derp.stun_port }}
      protocol: UDP
{{- end }}