apiVersion: v2
name: tailscale-derp
description: Tailscale DERP Relay Server Helm Chart
home: https://github.com/sspreitzer/helm-tailscale/tree/main/charts/tailscale-derp
sources:
  - https://github.com/sspreitzer/helm-tailscale.git
maintainers:
  - name: dev.cm
    email: admin@dev.cm
    url: https://github.com/devcm-repo
icon: https://tailscale.com/files/apple-touch-icon.png
version: 1.44.0
appVersion: 1.44.0
