image:
  name: docker.io/devcm/tailscale-derp
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  annotations: {}

nodeSelector: {}

affinity: {}

tailscale:
# hostname: ''
  auth_key: ''

drep:
  hostname: derp.examples.com
# addr: ''
  verify_clients: true
