image:
  name: docker.io/devcm/tailscale-derp
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  annotations: {}

hostNetwork: false

nodeSelector: {}

affinity: {}

derp:
  hostname: derp.examples.com
  verify_clients: false
  http_port: 80
  https_port: 443
  stun_port: 3478
