apiVersion: v2
name: aiapi
description: New API and CLIProxyAPI Helm Chart
home: https://devcm-repo.github.io/helm-charts/
sources:
  - https://github.com/devcm-repo/helm-charts
maintainers:
  - name: dev.cm
    email: admin@dev.cm
    url: https://github.com/devcm-repo
version: 0.0.2
appVersion: latest
dependencies:
  - name: postgresql
    version: 18.6.2
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
  - name: valkey
    version: 5.4.11
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: valkey.enabled
