{{- if .Values.persistence.enabled }}
{{- $pvcName := printf "%s-%s-data" .Release.Name .Chart.Name }}
{{- if or (not .Values.persistence.checkExisting) (not (lookup "v1" "PersistentVolumeClaim" .Release.Namespace $pvcName)) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $pvcName }}
  {{- if .Values.persistence.data.annotations }}
  annotations:
    {{- range $key, $value := .Values.persistence.data.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.data.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
  {{- if .Values.persistence.data.storageClass }}
  storageClassName: {{ .Values.persistence.data.storageClass }}
  {{- end }}
{{- end }}
{{- end }}
